@startuml Simple Services

participant Client
participant "Server" as Server
database DB
queue Redis
participant "Celery Worker" as Worker


Client -> Server: Do Task
activate Server

Server ->DB: Create Task
Server -> Redis: Assign Task

Worker <- Redis: Do Task
activate Worker

Client <- Server: Task Created
deactivate Server

loop until task done
    Client -> Server: Query Task
    Server -> DB: Query Task Id
    Server <- DB: Task Id
    Server -> Redis: Query Task
    Server <- Redis: Task Status
    Client <- Server: Task Status
end loop

' Worker -> Redis: Task Done
Worker -> DB: Task Done

deactivate Worker

@enduml