@startuml workflow

participant Client
participant "Server" as Server
participant "Server:service" as ServerS
database DB
box "Celery Ecosystem"
queue Redis
participant "Celery Worker" as Worker
end box

activate ServerS

Client -> Server: Do Task
activate Server

Server -> DB: Create Task
Server -> Redis: Assign Celery Task
note right of Redis
    Redis has **broker** and **backend** roles
end note

Server -> Client: Task Created
deactivate Server

Worker <- Redis: Do Celery Task
activate Worker

loop
    Worker -> Redis: Celery Task Progress
    ServerS <- Redis: Celery Task Progress
    ServerS --> Client: Task Progress
end loop
Worker -> Redis: Celery Task Done
deactivate Worker

ServerS <- Redis: Celery Task Done
ServerS -> DB: Update Task
ServerS --> Client: Task Done


@enduml