# pull official base image
FROM node:latest

# set work directory
WORKDIR /app

# set environment variables
ENV HOST=0.0.0.0
ENV PORT=3000

# install dependencies
COPY package.json package-lock.json* ./
RUN npm install

EXPOSE 3000